# Generated by Django 5.0.2 on 2024-02-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(blank=True, default='61052944', max_length=8, null=True, verbose_name='Код подтверждения'),
        ),
    ]
